addpath('hdf5matlab')

todata = ['..' filesep '..' filesep 'BicycleDAQ' filesep 'data']

load([todata filesep '00170.mat'])

hdf5save([todata filesep 'h5' filesep '00170.h5'], ...
         'InputPairs', 'InputPairs', ...
         'NIData', 'NIData', ...
         'VNavCols', 'VNavCols', ...
         'VNavData', 'VNavData', ...
         'VNavDataText', 'VNavDataText', ...
         'par', 'par')
